### PR TITLE
Update ResultStore

### PR DESCRIPTION
**Pull request by vsebe**
Update ResultStore host. Use local copy for AIX.

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
@llxia please review but do not merge yet, thank you!

**Comment by llxia** [comment]
@renfeiw Not specific to this PR. Could we move ResultStore logic internally?

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by renfeiw** [comment]
> @renfeiw Not specific to this PR. Could we move ResultStore logic internally?

Yes, I think we should port it to internal.

**Comment by vsebe** [comment]
@llxia could you please review, thank you!

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
@renfeiw is testing internal TKG. I will leave it to him to merge.

**Pull request merged**
