### PR TITLE
Add follow redirect in querying

### PR DESCRIPTION
**Pull request by annaibm**
- Added `-L` to support http TRSS URL.

resolves: https://github.com/adoptium/TKG/issues/555

### CODE REVIEW

**Comment by llxia** [comment]
@annaibm can you also print the exception after https://github.com/adoptium/TKG/pull/556/files#diff-5c4952a8e594a0cc890b8f28d53d76fe77c7e1c75dadc24e634bf781feea396dL243

**Review by llxia — APPROVED** [review]

**Comment by llxia** [comment]
TKG parsing issue will be tracked via https://github.com/adoptium/TKG/issues/558

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Comment by annaibm** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_ppc64_aix/718/

**Pull request merged**
