### PR TITLE
Add exclude file for value type standard build

### PR DESCRIPTION
**Pull request by hangshao0**
issue: https://github.com/eclipse-openj9/openj9/issues/12878

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
@llxia

**Comment by llxia** [comment]
This PR needs to be merged together with https://github.com/eclipse-openj9/openj9/pull/12879

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
run aqa --sdk_resource nightly --build_list functional --target sanity.functional.regular --jdk_version 11 --jdk_impl openj9 --platform x86-64_windows

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
