### PR TITLE
Update osLabel detection

### LINKED ISSUE #436: OS detection for CentOS
We added OS detection in TKG https://github.com/adoptium/TKG/issues/417 (thanks @renfeiw). It supports rhel, ubuntu, sles atm. We would also need to add OS detection for Cent as we have a few PPC Cent machines for CRIU testing.

FYI @tajila @renfeiw

### PR DESCRIPTION
**Pull request by renfeiw**
- supports cent os
- fix supported os logic

Fixes #436

### CODE REVIEW

**Comment by renfeiw** [comment]
Grinder_TKG/1883, Grinder_TKG/1884, Grinder_TKG/1885

**Comment by renfeiw** [comment]
run tkg-test -t platformRequirements -v

**Comment by renfeiw** [comment]
Grinder_TKG/1889, Grinder_TKG/1890, Grinder_TKG/1891

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by karianna — APPROVED** [review]

**Pull request merged**
