### PR TITLE
Update jtreg jar

### LINKED ISSUE #213: Update dependency jtreg version
Similar issue to  https://github.com/adoptium/aqa-tests/issues/2642

### PR DESCRIPTION
**Pull request by sophia-guo**
Close #213 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Convert to draft as this may need to cooperate with PR in other repos and rerun some jenkins build.

**Review by karianna — APPROVED** [review]
LGTM - noticed that the jtreg jars are named a little differently but that's OK.

**Comment by sophia-guo** [comment]
Yes, @karianna. Naming to be consistent with jtreg releases. https://github.com/openjdk/jtreg/releases

**Comment by llxia** [comment]
test.dependency on all Jenkins need to be relaunched after this PR

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/job/test.getDependency/1105

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/test.getDependency/34/

**Pull request merged**
