### PR TITLE
Added mvn check

### PR DESCRIPTION
**Pull request by sophiaxu0424**
Issue related to: https://github.com/adoptium/TKG/issues/567

### CODE REVIEW

**Comment by sophiaxu0424** [comment]
Passed tests with maven installed:https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41309/
```
14:51:35  mavenVersion : 
14:51:35  	Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
14:51:35  	Maven home: /usr/local/apache-maven-3.6.3
```

**Comment by sophiaxu0424** [comment]
and mvn not installed on an aix platform here, but test passed: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41310/:
```
 mavenVersion : bash: line 1: mvn: command not found
```

**Comment by sophiaxu0424** [comment]
@llxia @LongyuZhang please kindly review. thanks!

**Review by llxia — APPROVED** [review]

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
