### PR TITLE
Ensure TestInfoParser gets correct platform element

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
getElementsByTagName("platform") returns all platform nodes in the document including child ones from any <disabled> sections. This PR finds the <platform> element that is directly within the parent element. 

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
Fixes https://github.com/adoptium/TKG/pull/225

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target _sanity --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by renfeiw** [comment]
> Fixes #225

Could you please update the issue link?

**Review by renfeiw — APPROVED** [review]
Thanks, LGTM.

**Review by llxia — APPROVED** [review]
LGTM. Thanks @andrew-m-leonard for fixing this :)

**Pull request merged**
