### PR TITLE
Update resultSum parsing logic

### PR DESCRIPTION
**Pull request by renfeiw**
fixes: [#3792](https://github.com/adoptium/aqa-tests/issues/3792)

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5686/

**Comment by llxia** [comment]
Please also test with a group of tests (i.e., sanity.openjdk).

**Comment by renfeiw** [comment]
> Please also test with a group of tests (i.e., sanity.openjdk).

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5689

**Review by llxia — APPROVED** [review]
Thanks @renfeiw

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
