### PR TITLE
Enhance TKG repeat feature

### PR DESCRIPTION
**Pull request by renfeiw**
- add ITERATIONS and AOT_ITERATIONS options
- add option to continue or stop after failure is detected

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
related: #352

**Comment by llxia** [comment]
Could you update TKG_REPEAT and AOT_REPEAT to ITERATIONS and AOT_ITERATIONS in the description? Thanks

**Comment by renfeiw** [comment]
> Could you update TKG_REPEAT and AOT_REPEAT to ITERATIONS and AOT_ITERATIONS in the description? Thanks

Thanks updated.

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
Thanks @renfeiw, this is nice!  I ran an open [Grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5703/) to see what the console output looks like.  

Note to self: We can likely revert/remove this [change](https://github.com/adoptium/aqa-tests/pull/1576/files) in Jenkinsfilebase given it is no longer needed to show iteration progress (and only works for Jenkins environment)

**Comment by smlambert** [comment]
If I look at the console output, there is a change required in Jenkinsfilebase so that we do not multiply ITERATIONS by ITERATIONS, as I think we both run the make target ITERATIONS times, but also have a for loop in runTest() in Jenkinsfilebase, which we will need to remove or end up running ITERATIONS<sup>2</sup>.

Not sure if we want to merge this first or coordinate a PR to update Jenkinsfilebase and merge together.

**Comment by renfeiw** [comment]
Yes, it would be better to merge together with this PR: https://github.com/adoptium/aqa-tests/pull/3989

**Comment by renfeiw** [comment]
PR build: https://github.com/adoptium/aqa-tests/pull/3989

**Comment by llxia** [comment]
hmm, we only have 1 TAP for the Grinder. I cannot tell we had 3 iterations in the TAP file https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5709/tapResults/

**Comment by renfeiw** [comment]
> hmm, we only have 1 TAP for the Grinder. I cannot tell we had 3 iterations in the TAP file https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5709/tapResults/

This is the next step we need to add the iteration info into result summary.

**Comment by renfeiw** [comment]
Just had a discussion with @llxia We think it's not the right stage to switch over completely to TKG iteration. So I will update the PR to use TKG_ITERATIONS and it will not conflict with Jenkins ITERATIONS.

**Comment by renfeiw** [comment]
grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5712/

**Pull request merged**
