### PR TITLE
Fix issue with compressed detection

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Fix: https://github.com/eclipse-openj9/openj9/issues/13106

**Comment by renfeiw** [comment]
Grinder with fix: Grinder_TKG/1277

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
sneaky braces!

**Pull request merged**
