### PR TITLE
Fix machineInfo curl validation

### PR DESCRIPTION
**Pull request by renfeiw**
- based on #457
- provide fix for NumberFormatException

### CODE REVIEW

**Comment by renfeiw** [comment]
fyi @KostasTsiounis

**Comment by renfeiw** [comment]
Internal grinders: Grinder/33973 - Grinder/33979 
https://openj9-jenkins.osuosl.org/job/Grinder/2590/

**Review by karianna — CHANGES_REQUESTED** [review]
should we remove commented out code?

**Comment by renfeiw** [comment]
> should we remove commented out code?

This is a fixed version based on the last PR, as the last one was reverted. Removing the commented out and provide a toggle option can be an update in another PR.

**Review by llxia — APPROVED** [review]

**Review by karianna — APPROVED** [review]

**Pull request merged**
