### PR TITLE
Moving LIB_DIR visible for all make process

### PR DESCRIPTION
**Pull request by sophia-guo**
Fix https://github.com/adoptium/aqa-tests/issues/4914

### CODE REVIEW

**Comment by sophia-guo** [comment]
Grinder https://ci.adoptium.net/view/Test_grinder/job/Grinder/8216/
parallel https://ci.adoptium.net/view/Test_grinder/job/Grinder/8217/ - cancelled as check the child jobs no lib issue.

**Comment by llxia** [comment]
We do not have any issues in Jenkins. This PR has to be validated in local runs or run aqa.

**Comment by sophia-guo** [comment]
It validates locally

**Review by smlambert — APPROVED** [review]
👍

**Review by llxia — APPROVED** [review]

**Pull request merged**
