### PR TITLE
Enable modes with balanced GC for AArch64

### PR DESCRIPTION
**Pull request by knn-k**
This commit enables modes with balanced GC for AArch64.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
What is the state of this draft @knn-k ?  Is the intention to still bring it in eventually ?

**Comment by knn-k** [comment]
I am still waiting for eclipse-openj9/openj9#10320 to be reviewed.

**Comment by knn-k** [comment]
https://github.com/eclipse-openj9/openj9/pull/10320 is merged now.

**Review by renfeiw — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]

**Pull request merged**
