### PR TITLE
Add platform in playlist.xsd

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=openjdk --target=sanity --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=openjdk --target=sanity --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Comment by renfeiw** [comment]
The failure is not related.

**Review by llxia — APPROVED** [review]

**Pull request merged**
