### PR TITLE
Remove debug print out

### PR DESCRIPTION
**Pull request by renfeiw**

### CODE REVIEW

**Comment by renfeiw** [comment]
run tkg-test

**Comment by renfeiw** [comment]
run tkg-test

**Comment by renfeiw** [comment]
run tkg-test

**Comment by renfeiw** [comment]
run tkg-test

**Comment by renfeiw** [comment]
run tkg-test -v

**Comment by renfeiw** [comment]
run tkg-test

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by karianna — APPROVED** [review]

**Pull request merged**
