### PR TITLE
Add OpenJCEPlus tests dependencies

### PR DESCRIPTION
**Pull request by JinhangZhang**

### CODE REVIEW

**Comment by JinhangZhang** [comment]
@llxia @jasonkatonica FYI

**Comment by llxia** [comment]
Thanks @JinhangZhang . Could you update the title and commit message to `Add OpenJCEPlus tests dependencies`? The current title is misleading.

This PR should only be merged with the OpenJCEPlus tests changes in https://github.com/adoptium/aqa-tests repo. I assume it will be created shortly.

**Review by karianna — APPROVED** [review]

**Comment by JinhangZhang** [comment]
Updated

> Thanks @JinhangZhang . Could you update the title and commit message to `Add OpenJCEPlus tests dependencies`? The current title is misleading.

**Review by llxia — APPROVED** [review]

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/test.getDependency/1110/

**Pull request merged**
