### PR TITLE
Modularizing TKG test

### LINKED ISSUE #445: Modularizing TKG testing
The test for TKG was built with a small amount of tests. Now it's embracing more and more tests and expect to have more in the future. Hence, we would like to create a simple framework/harness for TKG test and separate the test file into small modules and each of them has single responsibility. The framework could also automatically pick up any newly added test in the future. So we have multiple people work on it without interfering each other.

### PR DESCRIPTION
**Pull request by renfeiw**
- fixes #445

### CODE REVIEW

**Comment by renfeiw** [comment]
run tkg-test

**Comment by renfeiw** [comment]
run tkg-test -t test_base -v

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @renfeiw !

**Pull request merged**
