### PR TITLE
Add function getImmediateChildContent in TKG for better parsing

### PR DESCRIPTION
**Pull request by renfeiw**
- use common function getImmediateChildContent
- reorganize aot parser logic

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target _sanity --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target _sanity --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by renfeiw** [comment]
internal build: Grinder_TKG/1304

**Review by smlambert — APPROVED** [review]
LGTM, thanks!

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
