### PR TITLE
Create default spec

### LINKED ISSUE #341: Add a default spec
Most platforms do not need their own spec and would use the same set of [modes](https://github.com/adoptium/TKG/blob/master/resources/modes.xml) (standard set of command line options).  

Having a default spec, simplifies [ottawa.csv](https://github.com/adoptium/TKG/blob/master/resources/ottawa.csv) and will make it easier to add new platforms and also mean less need to change that file (which is awkward to change and a carry over from some old tooling that we have not removed ourselves from just yet).

### PR DESCRIPTION
**Pull request by renfeiw**
Fixes #341 
- add default modes in ottawa.csv
- when platform not found, fall back to default

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
Modified auto detection logic to test default case. 64-bits: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5356 32-bits: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5357

**Comment by renfeiw** [comment]
test on non-default case: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5385

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
LGTM, thanks for the Grinder links and proactive testing!

**Pull request merged**
