### PR TITLE
LL4 playlist migration

### PR DESCRIPTION
**Pull request by varshm16**
I have disabled the -Xgcpolicy:metronome modes (300 series modes)  in zlinux 64 and linux ppcle64 according to https://github.com/adoptium/TKG/pull/511

Linux IA32:
hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/15251/
Linux AMD64:
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/13255/
Linux PPC32:
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/13579/
Linux PPC64:
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/15252/
Linux PPCLE64:
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/15253/
Zlinux31:
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/13743/
Zlinux64:
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/15256/
AIX PPC32:
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/13625/
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/13747/
AIX PPC64:
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/13261/
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/13539/

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by llxia** [comment]
I would prefer to be cautious when merging changes in ottawa.csv, as it's difficult to discern what has been altered in the file. Please list which mode on which platform has changed, and why.

Also, please do full testing with the Semeru build.

**Comment by varshm16** [comment]
I have tested the enabled modes on Semeru 8 builds for the available platforms:
AIXPPC64-hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/16634/
Linux AMD64-hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/17576/
Linux arch64-hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/16635/ 
Linux ppcle64:hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/17577/
Windows :
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/17570/
Zlinux64:hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/17711/

**Review by karianna — APPROVED** [review]

**Comment by varshm16** [comment]
The below modes are enabled on the below platforms in order to run the LL4 playlist.

Mode 109-CS enabled on linux AMD64,Linux PPC64 and Zlinux64
Mode 110-cs enabled on linux AMD64,Linux PPC64 and Zlinux64
Mode 150-CS enabled on linux AMD64,Linux PPC64 and Zlinux64
Mode 159-CS enabled on linux AMD64,Linux PPC64 and Zlinux6
Mode 136 enabled on linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 138 enabled on linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 139 enabled on linux x86-32,linux ppc32,linux ppc64,linux 390-64,aixppc32
Mode 500:linux x86-32,linux ppc32,linux ppc64,zlinux 31,aixppc32
Mode 501:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 503:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 504:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 505:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 506:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 507:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 550:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 551:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 553:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 554:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 555:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 556:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 557:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 607:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 610:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 687:linux x86-32,linux ppc32,zlinux 31,aixppc32
Mode 688:linux x86-32,linux ppc32,zlinux 31,aixppc32

**Comment by llxia** [comment]
According to https://github.com/adoptium/TKG/pull/459#issuecomment-2536841194, close the issue.

**Pull request closed without merging**
