### PR TITLE
Add playlist validation

### PR DESCRIPTION
**Pull request by renfeiw**
- use xsd to validate playlist file before parsing

fixes: https://github.com/adoptium/TKG/issues/167

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target sanity.openjdk --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target sanity.openjdk --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by renfeiw** [comment]
internal tested: Grinder_TKG/1216

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target sanity.functional --jdk_version 11 --jdk_impl openj9 --platform x86-64_linux

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list functional --target sanity.functional --jdk_version 11 --jdk_impl openj9 --platform x86-64_linux

**Comment by renfeiw** [comment]
internal build: Grinder_TKG/1217

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @renfeiw !

**Pull request merged**
