### PR TITLE
Removed view/Dependencies from asmtools URL

### LINKED ISSUE #546: Remove view/Dependencies from asmtools URL
We should use a direct 3rd party downloading URL, not a view. If the view changes, the URL will be invalid.

https://github.com/adoptium/TKG/blob/e9d595ec71f6e33dba769424a4435823a70276d5/scripts/getDependencies.pl#L128

Remove `view/Dependencies` from the URL:

https://ci.adoptium.net/job/dependency_pipeline/lastSuccessfulBuild/artifact/asmtools/asmtools-core-7.0.b10-ea.jar

### PR DESCRIPTION
**Pull request by IamLRBA**
Fixes #546 
cc
@llxia 
@smlambert

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
I've added the 'closes' remark and will merge.  Thanks @IamLRBA !

**Comment by IamLRBA** [comment]
> I've added the 'closes' remark and will merge. Thanks @IamLRBA !

Thank you for the opportunity @smlambert, I will be on the lookout for other "good first issue" issues to help me contribute more to the community.

**Comment by smlambert** [comment]
> I will be on the lookout for other "good first issue" issues to help me contribute more to the community.

That will be wonderful @IamLRBA ... if you like to do more, we can pick out a few slightly bigger tasks to involve you in.  For example, it would be good to address this one, https://github.com/adoptium/TKG/issues/363

**Pull request merged**
