### PR TITLE
Use mac specific cpu command in MachineInfo

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/193

**Comment by renfeiw** [comment]
reviewers: @smlambert @llxia

**Review by smlambert — APPROVED** [review]
LGTM, thanks @renfeiw !

**Comment by smlambert** [comment]
@gdams - I do not see @llxia in the reviewer list (nor some other AQAvit committers and yet I see others that are Temurin committers that I would not expect to have write permissions in the test repos), can you verify they are now all added to the Github team with write permissions for this repo?

**Review by llxia — APPROVED** [review]

**Pull request merged**
