### PR TITLE
Modify platform requirements to support not operation

### PR DESCRIPTION
**Pull request by renfeiw**

### CODE REVIEW

**Comment by renfeiw** [comment]
run tkg-test

**Comment by renfeiw** [comment]
run tkg-test

**Comment by renfeiw** [comment]
run tkg-test

**Comment by renfeiw** [comment]
Grinder_TKG/1882

**Comment by renfeiw** [comment]
run tkg-test

**Comment by renfeiw** [comment]
run tkg-test -t platformRequirements -v

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
