### PR TITLE
Fail when test cannot be found in testList

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
output:
```
13:09:38  Error: cannot find the following tests: abc, def (note: group target such as sanity are not accepted inside testList)
```

**Comment by renfeiw** [comment]
Grinder/24673, Grinder/24674

**Review by smlambert — APPROVED** [review]
Thanks @renfeiw !

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
