### PR TITLE
Use cut instead of $CUT

### PR DESCRIPTION
**Pull request by RadekCap**
Add check of CUT.

CUT is needed for a proper setting of LIB_DIR in CYGWIN.

### CODE REVIEW

**Comment by sophia-guo** [comment]
cut is only use once for CYGWIN check [UNAME_OS := $(shell $(UNAME) -s | $(CUT) -f1 -d_)](https://github.com/adoptium/TKG/blob/master/makefile#L43). May just use `cut` instead.

**Comment by judovana** [comment]
@sophia-guo  can you  please elaborate more?  Do yo recomend to use `cut` instead `$(CUT)` ? Whats the benefit? The cut will still be missing from path. And it will enad as `command not found`...

I'm missing some detection of the cut. Where do you expect it to be set? Can  you point us?

**Comment by judovana** [comment]
@RadekCap  maybe you can add fallback?

if `$(CUT)` is missing, maybe yo may check path for `cut` it, and if it is there, then use that, if not then indeed die...

**Comment by sophia-guo** [comment]
I mean use `cut` directly there is no need to define `CUT` as it is used only once and presumably that will be true for a long time. 

@RadekCap and I have talked about it in a meeting and @RadekCap will update the PR accordingly.

**Comment by RadekCap** [comment]
@sophia-guo updated as requested.

I've added a debug message for LIB_DIR as well.

**Comment by judovana** [comment]
I think the verification that the cut is on path should be  done. Also i think that calling cut without $(CUT) is bad code.

**Comment by sophia-guo** [comment]
I think the `cut` command comes pre-installed in most Linux distributions. Though agreed though @judovana it doesn't hurt to verify.

**Review by karianna — APPROVED** [review]

**Review by sophia-guo — APPROVED** [review]

**Comment by judovana** [comment]
```
-UNAME_OS := $(shell $(UNAME) -s | $(CUT) -f1 -d_)
+UNAME_OS := $(shell $(UNAME) -s | cut -f1 -d_)
```

Just to summ this up - we agreed it should be checked - but  the patch was approvred without the check.
In addition we caused (microscopical) regression, that if I have CUT declared, it will be ignored.

Am I right or am reading it wrong? 

I know the proper gues/set/check if is nto exactly plesant, but Radek's original commit was very close to it.  Also I agree it is super minor thing, but I feel very very uncomfortable about it:( Do we agree on finish it properly (@RadekCap  please?), or do you really want to set this precedent?

**Pull request merged**
