### PR TITLE
Removed TEST_RESULTSTORE logic

### PR DESCRIPTION
**Pull request by SAY-droid427**
As per my understanding of the issue, I have removed the [lines 135 - 151](https://github.com/adoptium/TKG/blob/master/openj9Settings.mk#L135-L151).

Fixes https://github.com/adoptium/TKG/issues/61

### CODE REVIEW

**Comment by SAY-droid427** [comment]
@smlambert Please review the PR and let me know if anything else had to be done. Thanks!

**Review by smlambert — APPROVED** [review]
thanks @SAY-droid427 !

**Comment by renfeiw** [comment]
Thanks @SAY-droid427. Discussed with @llxia, we need to further verify it will not break any internal testing first.

**Comment by SAY-droid427** [comment]
Thanks for taking out the time for reviewing the PR!

**Review by karianna — APPROVED** [review]
LGTM

**Comment by renfeiw** [comment]
Looks like we are still using this feature internally, so we cannot remove it at this moment. We need to port it to internal first if we want to remove it. fyi @llxia

**Comment by llxia** [comment]
The original issue #61 was created at the time when the logic was in both internal and external version. Now, this logic is in external only, we cannot remove it. As @renfeiw mentioned, in order to remove it, we need to port the logic to internal first. Otherwise, vmfarm upload will break.

**Comment by karianna** [comment]
@SAY-droid427 - merge conflict

**Comment by SAY-droid427** [comment]
@karianna Resolved merge conflicts

**Comment by karianna** [comment]
@llxia has that internal change landed?

**Comment by llxia** [comment]
> @llxia has that internal change landed?

No, not yet

**Comment by karianna** [comment]
Converting to draft so we don't merge by accident until it's ready.

**Pull request closed without merging**
