### PR TITLE
Update jtreg6.1.1 name

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Fix https://github.com/adoptium/TKG/pull/247#issuecomment-970346423

@llxia

**Review by llxia — APPROVED** [review]
Thanks @sophia-guo

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/395/

**Pull request merged**
