### PR TITLE
Enhance platform requirements mechanism

### PR DESCRIPTION
**Pull request by renfeiw**
- the new feature utilize regex to specify platform

fixes https://github.com/adoptium/TKG/issues/166

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target sanity.openjdk --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target sanity.openjdk --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by renfeiw** [comment]
The failed test in workflow run is not related.

**Comment by renfeiw** [comment]
internal tested: Grinder_TKG/1215/

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target sanity.openjdk --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by renfeiw** [comment]
internal build: Grinder_TKG/1218

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
LGTM

**Pull request merged**
