### PR TITLE
Set test environment for zArtemis platforms

### PR DESCRIPTION
**Pull request by vsebe**
Set TR_Options environment variable for zArtemis platforms.

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
@llxia please review, thank you!

**Comment by vsebe** [comment]
@renfeiw please review, thank you!

**Review by llxia — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
