### PR TITLE
Detecting zLinux31 architecture

### LINKED ISSUE #208: TKG: Unable to detect zLinux31 architecture.
While executing SVT tests on zLinux31, TKG failed to detect system.os.arch as s390.

**Error:**
System.getProperty('os.arch')=s390
17:40:14  
17:40:14  System.getProperty('java.fullversion')=8.0.7.0 - pxz3180sr7-20210609_01(SR7)
17:40:14  JRE 1.8.0 Linux s390-31-Bit 20210608_6725 (JIT enabled, AOT enabled)
17:40:14  OpenJ9   - 46b10e7
17:40:14  OMR      - e4c94e9
17:40:14  IBM      - c24a144
17:40:14  
17:40:14  Cannot determine System.getProperty('os.arch')=s390
17:40:14  
17:40:14  makefile:66: recipe for target 'envDetect' failed

Link:- hyc-runtimes-jenkins.swg-devops.com/job/Grinder/16159

### PR DESCRIPTION
**Pull request by psoujany**
This PR fixes #208 
Signed-off-by: Pasam Soujanya psoujany@in.ibm.com

### CODE REVIEW

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
@psoujany could you provide Grinder link? Thanks

**Comment by psoujany** [comment]
Grinder where issue is seen
 hyc-runtimes-jenkins.swg-devops.com/job/Grinder/16159
 
 To verify the change, I need to modify scripts or is there a way I can pass my branch?

**Comment by psoujany** [comment]
Verification job with the changes.
hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/16284

/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java -cp ./bin/TestKitGen.jar org.openj9.envInfo.EnvDetector
11:41:31  System.getProperty('java.vm.name')=IBM J9 VM
11:41:31  
11:41:31  System.getProperty('java.vendor')=IBM Corporation
11:41:31  
11:41:31  System.getProperty('os.name')=Linux
11:41:31  
11:41:31  System.getProperty('os.arch')=s390
11:41:31  
11:41:31  System.getProperty('java.fullversion')=8.0.7.0 - pxz3180sr7-20210609_01(SR7)
11:41:31  JRE 1.8.0 Linux s390-31-Bit 20210608_6725 (JIT enabled, AOT enabled)
11:41:31  OpenJ9   - 46b10e7
11:41:31  OMR      - e4c94e9
11:41:31  IBM      - c24a144
11:41:31  
11:41:31  System.getProperty('sun.arch.data.model')=32

**Comment by llxia** [comment]
Thanks @psoujany 
In the future, you can use `Grinder_TKG` to verify the TKG changes.

**Review by llxia — APPROVED** [review]
LGTM

**Comment by psoujany** [comment]
Thanks @llxia .

**Pull request merged**
