### PR TITLE
Add mixed riscv spec

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1053/

**Comment by llxia** [comment]
In original riscv specs, most modes were purposely turn off. But the basic modes (Mode150, 650) need to turn on in this PR. Otherwise, tests with these modes will not run. For example:
https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L42

**Comment by renfeiw** [comment]
> In original riscv specs, most modes were purposely turn off. But the basic modes (Mode150, 650) need to turn on in this PR. Otherwise, tests with these modes will not run. For example:
> https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L42

Updated, thanks.

**Review by llxia — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
Grinder looks good: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1058/

**Review by smlambert — APPROVED** [review]
thanks @renfeiw !

**Pull request merged**
