### PR TITLE
Revert "Enable modes with balanced GC for AArch64"

### PR DESCRIPTION
**Pull request by knn-k**
Revert adoptium/TKG#97 for the time being, as failures were found with balanced GC on AArch64.

Signed-off-by: KONNO Kazuhiro konno@jp.ibm.com

### CODE REVIEW

**Comment by knn-k** [comment]
Examples of balanced GC failures:
- https://github.com/eclipse-openj9/openj9/issues/12831
- https://github.com/eclipse-openj9/openj9/issues/12832

**Review by smlambert — APPROVED** [review]

**Review by sophia-guo — APPROVED** [review]

**Comment by knn-k** [comment]
What can I do with "The author(s) of the pull request is not covered by necessary legal agreements in order to proceed." ?
I tried to revalidate my account, but the message does not change.

**Comment by karianna** [comment]
> What can I do with "The author(s) of the pull request is not covered by necessary legal agreements in order to proceed." ?
> I tried to revalidate my account, but the message does not change.

It appears that the email address you have associated with this account isn't listed as one that has signed the Eclipse CLA.

http://www.eclipse.org/legal/CLA.php

**Comment by smlambert** [comment]
"[Signed off by](https://docs.pi-hole.net/guides/github/how-to-signoff/)" with the address associated with the Eclipse account usually does it.

**Comment by knn-k** [comment]
I opened #200, and the eclipsefdn/eca check was successful in that PR.
Closing this PR.

**Pull request closed without merging**
