### PR TITLE
Support regex in feature tag

### PR DESCRIPTION
**Pull request by renfeiw**
- modified testInfo parser
- added new tests for feature tag

### CODE REVIEW

**Comment by renfeiw** [comment]
run tkg-test

**Comment by renfeiw** [comment]
grinders: Grinder/34931, Grinder/34933, Grinder/34934, Grinder/34935

**Review by llxia — APPROVED** [review]
Thanks @renfeiw

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
