### PR TITLE
Auto include testVar.mk in playlist

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
internal grinder: Grinder_TKG/1504

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
@renfeiw could you resolve the merge conflict? Thanks

**Review by smlambert — APPROVED** [review]

**Comment by renfeiw** [comment]
> @renfeiw could you resolve the merge conflict? Thanks

resolved, thank you.

**Pull request merged**
