### PR TITLE
Add Mode189 to test -Xtune:throughput

### PR DESCRIPTION
**Pull request by cjjdespres**
Fixes: eclipse-openj9/openj9/issues/14551
Signed-off-by: Christian Despres <despresc@ibm.com>

### CODE REVIEW

**Comment by cjjdespres** [comment]
Attn @mpirvu

**Comment by llxia** [comment]
As suggested in https://github.com/eclipse-openj9/openj9/issues/14551#issuecomment-1049251410, we would prefer to use `-Xtune:throughput` directly, not adding a new Mode. It is not necessary to create a Mode for a single jvm option that can run on all platforms. It will cause more maintenance. May I know the reason why this is needed?

**Comment by cjjdespres** [comment]
I don't think it's absolutely needed. I added it because of https://github.com/eclipse-openj9/openj9/issues/14551#issuecomment-1049234938, but I think we're both okay with it not being a new mode.

**Comment by cjjdespres** [comment]
If we go that way then this PR can be closed and I'll change the other PR so it uses the option directly.

**Pull request closed without merging**
