### PR TITLE
enabling disabled modes for XML tests

### PR DESCRIPTION
**Pull request by AshithaVijay**
Enabled skipped modes for SVT XML tests on AIX, Linux and ZOS Platform according to the platform requirements:

Test passing links in various platforms:
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12686/ - ppc_aix
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12687/ - ppc64_aix
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12688/ - ppc_linux
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12689/ - ppc64_linux
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12659/ - ppc64le_linux
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12844/ - s390_linux
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12683/ - s390x_linux
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12691/ - s390x_zos
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12692/ - s390_zos
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12693/ - x86-64_linux
hyc-runtimes-jenkins.swg-devops.com/Grinder_CR/12841/ - x86-32_linux

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
@AshithaVijay Can you sign the Eclipse CLA please

**Comment by AshithaVijay** [comment]
@karianna I have signed the Eclipse CLA.

**Comment by llxia** [comment]
Recently, we merged a similar PR https://github.com/adoptium/TKG/pull/499 and had to revert because it caused issues in the regular build. I would prefer to be cautious when merging changes in ottawa.csv, as it's difficult to discern what has been altered in the file. Please list which mode on which platform has changed, and why.

**Comment by karianna** [comment]
@AshithaVijay can you respond to @llxia please and we can try to close this off

**Comment by AshithaVijay** [comment]
Yes, will close this as this has unwanted commits. I will raise a new PR with required changes only.

**Comment by AshithaVijay** [comment]
Duplicate of https://github.com/adoptium/TKG/pull/582

**Pull request closed without merging**
