### PR TITLE
Add AQACert info in TAP file

### PR DESCRIPTION
**Pull request by llxia**
- Add AQACert info in TAP file
- Remove java -version beccause AQACert.log contains java -vesrion

resolves: https://github.com/adoptium/TKG/issues/313

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4996/

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4996/tapResults/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4996/artifact/aqa-tests/TKG/output_16551567377541/Grinder_20220613214405.tap/*view*/

**Review by renfeiw — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @llxia !

**Pull request merged**
