### PR TITLE
Add zos mixed spec

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target _sanity --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by llxia** [comment]
Grinder_TKG/1291/

**Review by llxia — APPROVED** [review]
LGTM

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target _sanity --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
Merging this PR now allows for this platform to be tested under automation for the July release.

**Pull request merged**
