### PR TITLE
Auto detect TEST_FLAG

### PR DESCRIPTION
**Pull request by renfeiw**
- auto detect criu
- add CRIU into TEST_FLAG
- generate detected TEST_FLAG

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
@renfeiw could we echo the TEST_FLAG value? It is hard to know if the value is set by auto-detect or not.

**Comment by renfeiw** [comment]
> @renfeiw could we echo the TEST_FLAG value? It is hard to know if the value is set by auto-detect or not.

Updated here:
https://github.com/adoptium/TKG/pull/269/files#diff-83c733d1f9b8501703238c8677db18fdd2ba8241c2a3eab33a256f8d1198ed68R286

**Comment by llxia** [comment]
Thanks @renfeiw 

```
00:04:36.227  set JAVA_HOME to /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image
00:04:36.227  set SPEC to linux_x86-64
00:04:36.227  set TEST_FLAG to CRIU
```
Grinder/21158/console

**Review by llxia — APPROVED** [review]
LGTM

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
