### PR TITLE
Added example test case for ^arch_390_z15+

### PR DESCRIPTION
**Pull request by annaibm**
related: https://github.com/adoptium/TKG/issues/471

### CODE REVIEW

**Comment by annaibm** [comment]
Grinder links
Z15:
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40646/
Pasted Graphic 1

Z14:
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40648/
Pasted Graphic

**Comment by llxia** [comment]
Thanks @annaibm . Could you run one more test on z13?

**Comment by annaibm** [comment]
> Thanks @annaibm . Could you run one more test on z13?

Tried on z14 for `test_not_arch_390_z15+`.
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40651/tapTestReport/

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
