### PR TITLE
Enabling skipped modes to LL2 tests for AIX and Linux Platform 

### PR DESCRIPTION
**Pull request by Edith-Mercy**
github.ibm.com/runtimes/backlog/issues/1107 - with ref. to the backlog issue made changes to verify that skipped tests are executed

The Skipped modes that is enabled are
109-CS,110-CS, 150-CS,159-CS,301,350,351,501,503,504,506,507,550,551,555,556,557,601,609,610,615,688.

hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/6015/ - aix_ppc
hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/6009/ - aix_ppc-64
hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/6007/ - linux_x86-64
hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/6008/ - linux_ppc
hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/6010/ - linux_ppc-64
hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/6011/ - linux_ppc-64_le
hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/6013/ - s390x_linux
hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/6043 - linux_x86
hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/5079 - s390_linux

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by Edith-Mercy** [comment]
@llxia Can you review this Pull request to merge the changes?

**Comment by llxia** [comment]
If we enable for mixed, then either nocmprssptrs or cmprssptrs should be also enabled.

**Comment by llxia** [comment]
@renfeiw could you also review this PR?

**Comment by renfeiw** [comment]
@Edith-Mercy Could you please address this comment: 

> If we enable for mixed, then either nocmprssptrs or cmprssptrs should be also enabled.

**Comment by Edith-Mercy** [comment]
@llxia For nocmprssptrs or cmprssptrs  enabling the modes in ottawa.csv is the first step as per my understanding, however, I'm not sure how to test these on jenkins runs (like what options or PLATFORM need to be specified to start the runs on these modes), Can you help me on the same..

**Review by karianna — APPROVED** [review]

**Review by karianna — APPROVED** [review]

**Review by llxia — CHANGES_REQUESTED** [review]
- -Xgcpolicy:metronome is not supported on zLinux. From a brief look, this PR enabled it on zLinux. Also, there is no testing on windows. Both show that this PR has not been fully tested.
- This PR is similar to https://github.com/adoptium/TKG/pull/527. Please explain.

**Review by llxia — CHANGES_REQUESTED** [review]
It’s unnecessary to request the review again without first addressing the concerns. Also, reiterate https://github.com/adoptium/TKG/pull/582#pullrequestreview-2177808606

**Comment by Edith-Mercy** [comment]
@llxia  PRs to enable modes for  https://github.com/adoptium/TKG/pull/582 and https://github.com/adoptium/TKG/pull/527 are merged into this PR

**Comment by llxia** [comment]
@Edith-Mercy Thanks for working on this. But you closed this PR  and deleted the `LL2_skipped_modes` branch 2 weeks ago, please open a new one.

**Comment by Edith-Mercy** [comment]
@llxia https://github.com/adoptium/TKG/pull/650 created new pull request

**Pull request closed without merging**
