### PR TITLE
Add Readme.md for the liveMonitor scripts

### PR DESCRIPTION
**Pull request by JeromeJu**
Add basic documentations and usage regarding user stories for the liveMonitor scripts

Fixes: https://github.com/adoptium/TKG/issues/280

Signed-off-by: Jerome Ju [jeromeqju@gmail.com](mailto:jeromeqju@gmail.com)

### CODE REVIEW

**Comment by JeromeJu** [comment]
```
jeromeju@Jeromes-MacBook-Pro TKG % make _sanity.openjdk | python3 -u scripts/liveMonitor_countTests/jtreg-monitor.py

============== MONITORING STDIN FOR JTREG RESULTS ==============

openjdk version "17.0.2" 2022-01-18
IBM Semeru Runtime Open Edition 17.0.2.0 (build 17.0.2+8)
Eclipse OpenJ9 VM 17.0.2.0 (build openj9-0.30.0, JRE 17 Mac OS X amd64-64-Bit Compressed References 20220127_94 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - 64cd399ca28 based on jdk-17.0.2+8)

Attempting to destroy all caches in cacheDir /Users/jeromeju/javasharedresources/

JVMSHRC806I Compressed references persistent shared cache "sharedcc_jeromeju" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
JVMSHRC005I No shared class caches available
0:00:13.373978 / ...ng/annotation/AnnotationType/AnnotationTypeDeadlockTest.java / {}
TEST (1) 0:00:00.000705 @ 2022-03-07 23:19:09): java/lang/annotation/AnnotationType/AnnotationTypeDeadlockTest.java Passed
0:00:13.374683 / ...ng/annotation/AnnotationType/AnnotationTypeDeadlockTest.java / {'Passed': 1}
0:00:13.760148 / java/lang/HashCode.java / {'Passed': 1}                                        
TEST (2) 0:00:00.000953 @ 2022-03-07 23:19:10): java/lang/HashCode.java Passed
0:00:13.761101 / java/lang/HashCode.java / {'Passed': 2}
0:00:14.111257 / java/lang/Compare.java / {'Passed': 2} 
TEST (3) 0:00:00.001275 @ 2022-03-07 23:19:10): java/lang/Compare.java Passed
0:00:14.112532 / java/lang/Compare.java / {'Passed': 3}
0:00:14.112637 / java/lang/IntegralPrimitiveToString.java / {'Passed': 3}
TEST (4) 0:00:00.001267 @ 2022-03-07 23:19:10): java/lang/IntegralPrimitiveToString.java Passed
0:00:14.113904 / java/lang/IntegralPrimitiveToString.java / {'Passed': 4}
0:00:14.114100 / java/lang/ToString.java / {'Passed': 4}                 
TEST (5) 0:00:00.001127 @ 2022-03-07 23:19:10): java/lang/ToString.java Passed
0:00:14.11522

```

**Comment by JeromeJu** [comment]
Updated, the formated result can be viewed at:
https://github.com/JeromeJu/TKG/tree/test_doc/scripts/liveMonitor_countTests

**Review by smlambert — APPROVED** [review]
Excellent, thanks @JeromeJu !

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
